
service: aws-lambda-api-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"
  

# you can overwrite defaults here
  stage: dev
  profile: deploy-aws
  region: eu-central-1


functions:
  hello:
    handler: handler.getElement
    events:
      - http:
          method: get
          path: /signeblock
          cors: true
  goodbye:
    handler: handler.createElement
    events:
      - http:
          method: post
          path: /signeblock
          cors: true
resources:
  Resources:
    serviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: example-signeblock
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
